<script setup>
definePageMeta({
    layout: 'blog'
});

useHead({
    title: 'Blog'
});
</script>

<template>
    <h1>Blog Page</h1>
    <p>
        this is the blog page. It is a static page that is not generated by Nuxt.
    </p>
</template>