<script setup>
definePageMeta({
    layout: 'app'
})
</script>


<template>
    Project Page
    <p>
        This is the project page. It is a static page that is not generated by Nuxt.
    </p>
</template>