<script setup>
definePageMeta({
    layout: 'app'
});

useHead({
    title: 'Project'
});

const project = await $fetch('https://api.github.com/users/siihasann/repos')
console.log(project);
</script>


<template>
    Project Page
    <p>
        This is the project page. It is a static page that is not generated by Nuxt.
    </p>
</template>